###
POST http://localhost:5000/api/todos
Content-Type: application/json

{
	"name": "Photo's Job",
	"author": "nonami",
	"uid": "1919",
	"isComplete": true
}
###
POST http://localhost:5000/api/signup
Content-Type: application/json

{
	"name": "sayaka",
	"email":"sayaka@gmail.com",
	"password": "sayaka1919"
}
###
POST http://localhost:5000/api/signin
Content-Type: application/json

{
	"email":"yukie@gmail.com",
	"password": "yukie1919"
}

###
GET http://localhost:5000/api/todos
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTQxN2NlN2JlZjA5ZWEzYmIyNTU5ODgiLCJuYW1lIjoic2F5YWthIiwiZW1haWwiOiJzYXlha2FAZ21haWwuY29tIiwiaWF0IjoxNjMxNjgxNzY3fQ.0U_v5ormkEFZZLzr0SrB1ne37pBE127oTzofDG20UEI

{
	"name": "nonami",
	"author": "",
	"uid": "1919",
	"isComplete": true
}

###
PUT   http://localhost:5000/api/todos/6141491afa0c9f78c4da38ce
Content-Type: application/json

{
	"name": "New Gravure",
	"author": "nonami",
	"uid": "1919",
	"isComplete": false
}
###
PATCH    http://localhost:5000/api/todos/6141491afa0c9f78c4da38ce
Content-Type: application/json

{
	"name": "New Gravure",
	"author": "nonami",
	"uid": "1919",
	"isComplete": false
}

###
DELETE  http://localhost:5000/api/todos/61414a7bfa0c9f78c4da38d2
Content-Type: application/json

